### ISSUE TITLE
Configure the number of columns

### ISSUE THREAD

**Issue by shadow0013** [NerdyPepper/dijo#109]
On smaller screens (Termux on Android), it would be helpful if we can configure the number of colums to two instead of three.

**Comment by NerdyPepper** [comment]
This feature is now available on the [`grid-width`](https://github.com/NerdyPepper/dijo/tree/grid-width) branch. I'll have to polish it a bit more (the statusline clips on smaller widths etc.), but you can build from source and enable it in the config file (`~/.config/dijo/config.toml` on most gnu/linux machines) like so:

```toml
[look]
grid_size = 2 # set this to the number of items you want per row
```

Give it a go and let me know what you think!
