### ISSUE TITLE
Remapping keys

### ISSUE THREAD

**Issue by 00001** [NerdyPepper/dijo#47]
Would be nice to be able to remap keys.

I use dvorak, and the the movement keys htns instead of hjkl.

**Comment by michaelowens** [comment]
Would like to see this as well now, especially considering the keybinding `q` (to close dijo) was removed recently. Instead of pressing 1 key, I now have to press 4 (shift + : + q + enter). Would be nice to see this configurable as well :smile:

**Comment by NerdyPepper** [comment]
Should be possible once a config file feature is implemented.

**Comment by 00001** [comment]
Environment variable would also work.

**Comment by NerdyPepper** [comment]
This is available as of v0.2.7, remains undocumented however. The following is a sample config for dvorak:

```toml
[look]
true_chr = "·"
false_chr = "·"
future_chr = "·"
grid_size = 2

[colors]
reached = "cyan"
todo = "magenta"
inactive = "light black"

[keybinds]
week_mode = "v"
global_week_mode = "V"

[keybinds.grid]
up = "n"
down = "t"
left = "h"
right = "s"

[keybinds.cursor]
up = "N"
down = "T"
left = "H"
right = "S"
```
